apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
  namespace: default
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: plaintext
  selector:
    app: kafka