apiVersion: v1
kind: Service
metadata:
  name: academia-main-srv
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "academia-backend-config"}'
spec:
  selector:
    app: academia-main
  ports:
  - name: academia-main
    protocol: TCP
    port: 3001
    targetPort: 3001