apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.main.backendConfigName }}
  namespace: {{ .Values.namespace }}
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    port: {{ .Values.main.servicePort }}
    requestPath: /healthz