apiVersion: apps/v1
kind: Deployment
metadata:
  name: academia-transcoder-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academia-transcoder
  template:
    metadata:
      labels:
        app: academia-transcoder
    spec:
      containers:
      - name: academia-transcoder
        image: meghajmb/academia-transcoder:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: academia-transcoder-configs
        - secretRef:
            name: academia-transcoder-secrets
        resources:
          limits:
            cpu: "0.1"
            memory: "400Mi"
          requests:
            cpu: "0.05"
            memory: "200Mi"