apiVersion: apps/v1
kind: Deployment
metadata:
  name: academia-main-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academia-main
  template:
    metadata:
      labels:
        app: academia-main
    spec:
      containers:
      - name: academia-main
        image: meghajmb/academia-main:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: academia-main-configs
        - secretRef:
            name: academia-main-secrets
        resources:
          limits:
            cpu: "0.1"
            memory: "400Mi"
          requests:
            cpu: "0.05"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: academia-main-srv
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "academia-backend-config"}'
spec:
  selector:
    app: academia-main
  ports:
  - name: academia-main
    protocol: TCP
    port: 3001
    targetPort: 3001