name: deploy-main

on:
  push:
    branches:
      - main
    paths:
      - 'main/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: cd main && docker build -t $DOCKERHUB_USERNAME/academia-main:latest .

      - name: Push Image
        run: docker push $DOCKERHUB_USERNAME/academia-main:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2

      - name: Rollout restart deployment
        run: kubectl rollout restart deployment academia-main-depl -n default
